# -*- coding: utf-8 -*-
"""MDD_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVmLt_bn6-KNAuFquGNENYirwzwZPzKW
"""

import yfinance as yf
import pandas as pd
from datetime import datetime

# 1. 사용자로부터 입력 받기
print("--- 분석 설정 ---")
ticker_symbol = input("종목 코드를 입력하세요 (예: ^GSPC, SPY, AAPL): ")
start_date = input("시작 날짜를 입력하세요 (YYYY-MM-DD): ")
end_input = input("종료 날짜를 입력하세요 (YYYY-MM-DD, 미입력 시 오늘): ")

if not end_input:
    end_date = datetime.now().strftime('%Y-%m-%d')
else:
    end_date = end_input

# 2. 데이터 불러오기
print(f"\n{ticker_symbol} 데이터를 {start_date}부터 {end_date}까지 불러오는 중...")
df = yf.download(ticker_symbol, start=start_date, end=end_date, auto_adjust=True)
# 3. 데이터 확인
if not df.empty:
    print("\n[데이터 로드 완료]")
    print(df.head())
else:
    print("\n[오류] 데이터를 불러오지 못했습니다. 종목 코드나 날짜를 확인해 주세요.")

if not df.empty:
    # 1. 데이터 추출 (최신 버전 문법에 맞춰 안전하게 추출)
    if isinstance(df.columns, pd.MultiIndex):
        close_series = df['Close'][ticker_symbol]
    else:
        close_series = df['Close']

    # 2. 계산 수행
    rolling_max = close_series.cummax()
    drawdown = (close_series - rolling_max) / rolling_max * 100

    # 3. 현재 시점 데이터 추출
    current_price = float(close_series.iloc[-1])
    all_time_high = float(rolling_max.max())
    current_drawdown = float(drawdown.iloc[-1])

    # 4. 기준점 계산
    base_5  = all_time_high * 0.95
    base_10 = all_time_high * 0.90
    base_20 = all_time_high * 0.80
    base_30 = all_time_high * 0.70

    # 5. 결과 출력 (톤 유지!)
    print(f"\n===== {ticker_symbol} 분석 결과 =====")
    print(f"▶ 현재 주가: {current_price:,.2f}")
    print(f"▶ 기간 내 전고점: {all_time_high:,.2f}")
    print(f"▶ 전고점 대비 하락률: {current_drawdown:.2f}%")

    print(f"\n----- 진입 기준점 (전고점에서 빠질 때) -----")
    print(f"● 기준 0 (-5%  눌림목): {base_5:,.2f}")
    print(f"● 기준 1 (-10% 조정 지점): {base_10:,.2f}")
    print(f"● 기준 2 (-20% 하락 지점): {base_20:,.2f}")
    print(f"● 기준 3 (-30% 폭락 지점): {base_30:,.2f}")

if not df.empty:
    # 1. 전체 기간 중 가장 깊었던 하락(MDD) 계산
    real_mdd_value = drawdown.min()
    real_mdd_date = drawdown.idxmin()

    # 2. 그때 당시의 전고점과 실제 가격
    mdd_price = float(close_series.loc[real_mdd_date])
    peak_before_mdd = float(rolling_max.loc[real_mdd_date])

    # 3. 결과 출력
    print(f"\n===== {ticker_symbol} 역사적 데이터 분석 결과 =====")
    print(f"▶ 분석 기간: {start_date} ~ {end_date}")
    print(f"▶ 기간 내 최고가(MAX): {all_time_high:,.2f}")

    print(f"\n[가장 깊은 하락 (MDD)]")
    print(f"● 최대 낙폭: {real_mdd_value:.2f}%")
    print(f"● 발생 날짜: {real_mdd_date.strftime('%Y-%m-%d')}")
    print(f"● 당시 상황: 전고점 {peak_before_mdd:,.2f}에서 {mdd_price:,.2f}까지 추락")

if not df.empty:
    # 1. 엑셀의 COUNTA 역할 (전체 데이터 개수)
    total_days = len(drawdown)

    mdd_thresholds = [0, -5, -10, -15, -20, -25, -30, -35, -40, -45, -50, -60, -70, -80, -90]
    distribution_stats = []

    for t in mdd_thresholds:
        # 2. COUNTIF(범위, ">="&기준) 역할
        days_below_t = len(drawdown[drawdown <= t])

        # 3. 비율 계산 (COUNTIF / COUNTA)
        ratio = (days_below_t / total_days) * 100

        distribution_stats.append([f"{t}%", f"{ratio:.1f}%"])

    # 4. 결과 출력
    dist_df = pd.DataFrame(distribution_stats, columns=['MDD 기준', '비중(확률)'])
    print(f"\n===== {ticker_symbol} 하락 구간별 체류 비중  =====")
    print(f" (전체 분석 일수: {total_days}일)")
    print("-" * 40)
    print(dist_df.to_string(index=False))
    print("-" * 40)

if not df.empty:
    # 1. 현재 하락 사이클 분석
    # 전고점을 찍었던 마지막 날 찾기
    last_ath_date = rolling_max[rolling_max == close_series].index[-1]
    days_since_start = (drawdown.index[-1] - last_ath_date).days

    # 2. 하락 깊이별 회복 기간 분석 (함수화)
    def get_recovery_by_depth(target_dd):
        durations = []
        is_active = False
        s_date = None

        for date, dd in drawdown.items():
            # 타겟 하락률(예: -10%)에 도달한 순간 시작
            if not is_active and dd <= target_dd:
                is_active = True
                s_date = date
            # 다시 전고점(0)으로 복귀하면 종료
            elif is_active and dd >= 0:
                durations.append((date - s_date).days)
                is_active = False
        return durations

    depths = [-5, -10, -20, -30]
    depth_stats = []

    for d in depths:
        res = get_recovery_by_depth(d)
        if res:
            depth_stats.append([f"{d}% 이하", f"{len(res)}번", f"{np.mean(res):.1f}일", f"{np.max(res)}일"])
        else:
            depth_stats.append([f"{d}% 이하", "0번", "-", "-"])

    # 3. 결과 출력
    print(f"\n===== {ticker_symbol} 현재 하락 사이클 상태 =====")
    print(f"▶ 하락 시작일 (마지막 전고점): {last_ath_date.strftime('%Y-%m-%d')}")
    print(f"▶ 현재 하락 진행 일수: {days_since_start}일째")
    print(f"▶ 현재 하락률: {current_drawdown:.2f}%")

    print(f"\n===== 하락 깊이별 과거 회복 소요 시간 (평균) =====")
    stats_df = pd.DataFrame(depth_stats, columns=['하락 깊이', '발생 횟수', '평균 회복일', '최대 회복일'])
    print(stats_df.to_string(index=False))

import matplotlib.pyplot as plt

# 1. 그래프 설정
plt.figure(figsize=(15, 7))

# 2. MDD 선 그리기 (시간 흐름에 따른 하락률)
plt.plot(drawdown.index, drawdown, color='red', linewidth=1, label='Drawdown (%)')

# 3. 바닥을 채워주면 골짜기 느낌이 나서 더 보기 좋습니다 (선택 사항)
plt.fill_between(drawdown.index, drawdown, 0, color='red', alpha=0.2)

# 4. 주요 기준선 추가 (우리가 설정한 base_5, 10, 20, 30 등)
plt.axhline(y=-5, color='orange', linestyle='--', linewidth=1, label='-5% (Adjustment)')
plt.axhline(y=-10, color='darkorange', linestyle='--', linewidth=1, label='-10% (Correction)')
plt.axhline(y=-20, color='crimson', linestyle='--', linewidth=1, label='-20% (Bear Market)')

# 5. 그래프 꾸미기
plt.title(f'[{ticker_symbol}] Historical Drawdown Trend', fontsize=16)
plt.ylabel('Drop from Peak (%)', fontsize=12)
plt.xlabel('Date', fontsize=12)
plt.legend(loc='lower left')
plt.grid(True, alpha=0.3)

# 6. 현재 상태 표시
current_date = drawdown.index[-1]
plt.annotate(f'Current: {current_drawdown:.2f}%',
             xy=(current_date, current_drawdown),
             xytext=(current_date, current_drawdown - 5),
             arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=5),
             ha='center', fontweight='bold')

plt.tight_layout()
plt.show()